name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/test-reusable.yml
    with:
      godot_version: '4.4.1'

  build:
    needs: test
    uses: ./.github/workflows/build-reusable.yml
    with:
      use_matrix: true
      upload_artifacts: true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all AARs
        uses: actions/download-artifact@v4
        with:
          path: aars

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: aars/*/*.aar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
