name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      godot_version:
        required: false
        type: string
        default: '4.4.1'
      use_matrix:
        required: false
        type: boolean
        default: false

jobs:
  matrix-setup:
    uses: ./.github/workflows/matrix-setup.yml

  test:
    runs-on: ubuntu-latest
    needs: matrix-setup
    strategy:
      matrix:
        godot_version: ${{ inputs.use_matrix && fromJson(needs.matrix-setup.outputs.godot-versions) || fromJson(format('["{0}"]', inputs.godot_version)) }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup godot-lib
        run: |
          mkdir -p godot-lib
          filename="godot-lib.${{ matrix.godot_version }}.stable.template_release.aar"
          echo "configurations.maybeCreate(\"default\")" > godot-lib/build.gradle
          echo "artifacts.add(\"default\", file('$filename'))" >> godot-lib/build.gradle
          url="https://github.com/godotengine/godot/releases/download/${{ matrix.godot_version }}-stable/${filename}"
          curl -L -o "godot-lib/${filename}" "$url"

      - name: Run unit tests
        run: ./gradlew test --continue

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results Godot ${{ matrix.godot_version }}
          path: 'app/build/test-results/**/TEST-*.xml'
          reporter: java-junit
          fail-on-empty: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-godot-${{ matrix.godot_version }}
          path: |
            app/build/reports/tests/
            app/build/test-results/
